background = #131410
foreground = #e5e2dc
cursor-color = #c2cc97
selection-background = #2a2a26
selection-foreground = #e5e2dc

palette = 0=#353433
palette = 1=#a39200
palette = 2=#c3d55e
palette = 3=#e9ed6f
palette = 4=#95b37f
palette = 5=#c6a844
palette = 6=#bad285
palette = 7=#dbd9c2
palette = 8=#a5a391
palette = 9=#bdaa00
palette = 10=#d2e85c
palette = 11=#f5fc70
palette = 12=#b7c6a1
palette = 13=#d4be69
palette = 14=#cce58d
palette = 15=#ffffff
