[meta]
name = "Chadtain Dark"
description = "Earthy muted green/brown theme based on Chadtain palette"
variant = "dark"
inherits = "vicinae-dark"

[colors.core]
accent = "#4c685f"                # soft green highlight
accent_foreground = "#131C19"    # dark text on accent
background = "#131C19"
foreground = "#444F4C"
secondary_background = "#131c19"
border = "colors.core.background"

[colors.main_window]
border = "colors.core.background"
footer = { background = "colors.core.secondary_background" }

[colors.settings_window]
border = "#131c19"

[colors.accents]
blue = "#41575c"
green = "#4c685f"
magenta = "#5e526a"
orange = "#7a573f"
red = "#735959"
yellow = "#606F68"
cyan = "#395242"
purple = "#5e526a"

[colors.shortcut]
border = "colors.core.background"

[colors.text]
default = "#444F4C"
muted = "#606F68"
danger = "#735959"
success = "#4c685f"
placeholder = "#606F68"
selection = { background = "#395242", foreground = "#131C19" }

[colors.text.links]
default = "#4c685f"
visited = "#5e526a"

[colors.input]
border = "#131c19"
border_focus = "#4c685f"
border_error = "#735959"

[colors.button.primary]
background = "#2c382d"
foreground = "#444F4C"
hover = { background = "#395242" }
focus = { outline = "colors.core.accent" }

[colors.list.item.hover]
foreground = "#606F68"
secondary_foreground = "#606F68"

[colors.list.item.selection]
background = "#395242"
foreground = "#131C19"
secondary_background = "#395242"
secondary_foreground = "#131C19"

[colors.grid.item]
background = "#2c382d"
hover = { outline = "#444F4C" }
selection = { outline = "#4c685f" }

[colors.scrollbars]
background = "#2c382d"

[colors.loading]
bar = "#444F4C"
spinner = "#444F4C"
