#!/usr/bin/env fish
# _vicinae.fish — write Vicinae theme TOML and activate it.

set -l name      $THEME_NAME
set -l accent    (get_theme_val RED)
set -l bg        (get_theme_val BLACK)
set -l fg        (get_theme_val WHITE)
set -l d_black   (get_theme_val DARKER_BLACK)
set -l base01    (get_theme_val BASE01)
set -l base03    (get_theme_val BASE03)
set -l grey      (get_theme_val GREY)
set -l green     (get_theme_val GREEN)
set -l red       (get_theme_val RED)
set -l yellow    (get_theme_val YELLOW)
set -l teal      (get_theme_val TEAL)
set -l blue      (get_theme_val BLUE)
set -l pink      (get_theme_val PINK)
set -l baby_pink (get_theme_val BABY_PINK)
set -l purple    (get_theme_val PURPLE)

printf '%s\n' \
    '[meta]' \
    "name        = \"$name\"" \
    'description = "Generated by set_theme.fish"' \
    "variant     = \"$THEME_VARIANT\"" \
    'inherits    = "vicinae-dark"' \
    '' \
    '[colors.core]' \
    "accent               = \"$accent\"" \
    "accent_foreground    = \"$d_black\"" \
    "background           = \"$bg\"" \
    "foreground           = \"$fg\"" \
    "secondary_background = \"$bg\"" \
    'border               = "colors.core.background"' \
    '' \
    '[colors.main_window]' \
    'border = "colors.core.background"' \
    "footer = { background = \"colors.core.secondary_background\" }" \
    '' \
    '[colors.settings_window]' \
    'border = "colors.core.border"' \
    '' \
    '[colors.accents]' \
    "blue    = \"$teal\"" \
    "green   = \"$green\"" \
    "magenta = \"$baby_pink\"" \
    "orange  = \"$pink\"" \
    "red     = \"$red\"" \
    "yellow  = \"$yellow\"" \
    "cyan    = \"$teal\"" \
    "purple  = \"$purple\"" \
    '' \
    '[colors.shortcut]' \
    'border = "colors.core.border"' \
    '' \
    '[colors.text]' \
    "default     = \"$fg\"" \
    "muted       = \"$base03\"" \
    "danger      = \"$red\"" \
    "success     = \"$green\"" \
    "placeholder = \"$base03\"" \
    "selection   = { background = \"$grey\", foreground = \"$fg\" }" \
    '' \
    '[colors.text.links]' \
    "default = \"$teal\"" \
    "visited = \"$blue\"" \
    '' \
    '[colors.input]' \
    "border       = \"$bg\"" \
    "border_focus = \"$teal\"" \
    "border_error = \"$red\"" \
    '' \
    '[colors.button.primary]' \
    "background = \"$d_black\"" \
    "foreground = \"$fg\"" \
    "hover      = { background = \"$d_black\" }" \
    'focus      = { outline = "colors.core.accent" }' \
    '' \
    '[colors.list.item.hover]' \
    "foreground           = \"$fg\"" \
    "secondary_foreground = \"$base03\"" \
    '' \
    '[colors.list.item.selection]' \
    "background           = \"$base01\"" \
    "foreground           = \"$fg\"" \
    "secondary_background = \"$bg\"" \
    "secondary_foreground = \"$base03\"" \
    '' \
    '[colors.grid.item]' \
    "background = \"$bg\"" \
    "hover      = { outline = \"$fg\" }" \
    "selection  = { outline = \"$fg\" }" \
    '' \
    '[colors.scrollbars]' \
    "background = \"$bg\"" \
    '' \
    '[colors.loading]' \
    "bar     = \"$teal\"" \
    "spinner = \"$teal\"" \
    > ~/dots/vicinae-themes/$name.toml

and echo "set_theme.fish: wrote ~/dots/vicinae-themes/$name.toml"
or begin
    echo "set_theme.fish: failed to write vicinae config" >&2
    return 0
end

vicinae theme set $name
